frontend/app.py
from flask import Flask, render_template
from flask_cors import CORS
import os

from frontend.views import bias, opacity

app = Flask(__name__)
CORS(app, resources={r"/*": {"origins": "*"}})
app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'
UPLOAD_FOLDER = os.path.abspath("uploads")
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER


app.register_blueprint(bias.bp)
app.register_blueprint(opacity.bp)


@app.route('/', methods=['GET'])
def home():
    return render_template('homepage.html')


@app.route("/freqvsfreq")
def freqvsfreq():
    return render_template("/bias/freqvsfreq.html")

@app.route("/freqvsref")
def freqvsref():
    return render_template("/bias/freqvsref.html")

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001)

frontend/views/bias.py
import os
import subprocess
from subprocess import check_output

from flask import (Blueprint, Flask, Response, current_app, flash, jsonify,
                   redirect, render_template, request, session, url_for)

from frontend.views.bias_route import FreqvsFreq, FreqvsRef
from brio.utils.funcs import allowed_file, handle_multiupload

bp = Blueprint('bias', __name__,
               template_folder="../templates/bias", url_prefix="/bias")
bp.register_blueprint(FreqvsFreq.bp)
bp.register_blueprint(FreqvsRef.bp)

dict_vars = {}

used_df = ""
comp_thr = ""
success_status = "text-warning"
ips = check_output(['hostname', '-I'])
localhost_ip = ips.decode().split(" ")[0]
print(f"localhost_ip={localhost_ip}", flush=True)
# check if this script is being run inside a docker container
# if so, then the localhost_ip will be read from an environment variable
if os.system("test -f /.dockerenv") == 0:
    print("Running inside a docker container", flush=True)
    localhost_ip = os.environ['HOST_IP']
    print(f"localhost_ip={localhost_ip}", flush=True)



@bp.route('/', methods=['GET', 'POST'])
def home_bias():
    global used_df
    global success_status
    global dict_vars
    if request.method == 'GET' and request.args.get('reset'):
        used_df = ""
        success_status = "text-warning"
        dict_vars = {}
        session.clear()
    if request.method == 'POST':
        keys = list(request.files.keys())
        uploads = [request.files[x].filename for x in keys if x != '']
        if all(x == '' for x in uploads):
            flash('No files uploaded, try again!', 'danger')
            return redirect('/bias')
        if 'dataset' in list(request.files.keys()):
            dataframe_file = request.files['dataset']
            dict_vars['dataset'] = dataframe_file.filename
            if allowed_file(dict_vars['dataset']):
                dataframe_file.save(os.path.join(
                    current_app.config['UPLOAD_FOLDER'], dict_vars['dataset']))
                used_df = dict_vars['dataset']
                success_status = "text-success"
                flash('Dataframe uploaded successfully!', 'success')
            else:
                flash('Unsupported format for dataframe.', 'danger')
                return redirect('/bias')
        if ('dataset_custom' and 'notebook') in list(request.files.keys()):
            dict_vars['dataset_custom'] = request.files['dataset_custom'].filename
            dict_vars['notebook'] = request.files['notebook'].filename
            used_df = "Custom preprocessed " + dict_vars['dataset_custom']
            success_status = "text-success"
            if allowed_file(dict_vars['notebook']) and allowed_file(dict_vars['dataset_custom']):
                request.files['dataset_custom'].save(os.path.join(
                    current_app.config['UPLOAD_FOLDER'], dict_vars['dataset_custom']))
                request.files['notebook'].save(os.path.join(
                    current_app.config['UPLOAD_FOLDER'], dict_vars['notebook']))
            else:
                used_df = ""
                dict_vars = {}
                session.clear()
                success_status = "text-warning"
                flash('Unsupported format for notebook or dataset. Supported types for dataset are .pkl, .csv; for notebook supported types are .py, .ipynb', 'danger')
                return redirect('/bias')
            if request.files['artifacts'].filename != '':
                handle_multiupload(request, 'artifacts',
                                   current_app.config['UPLOAD_FOLDER'])
            notebook_extension = dict_vars['notebook'].split('.')[1]
            match notebook_extension:
                case 'ipynb':
                    os.system("jupyter nbconvert --to python " +
                              os.path.join(current_app.config['UPLOAD_FOLDER'], dict_vars['notebook']))
                    note_name = dict_vars['notebook'].split('.')[0]
                    subprocess.run(["python3", os.path.join(
                        current_app.config['UPLOAD_FOLDER'], note_name + ".py")])
                case 'py':
                    subprocess.run(["python3", os.path.join(
                        current_app.config['UPLOAD_FOLDER'], dict_vars['notebook'])])
            flash(
                'Custom preprocessing pipeline uploaded and processed successfully!', 'success')
        return redirect('/bias')
    return render_template('home.html', df_used=used_df, status=success_status)

frontend/views/opacity.py
from flask import Flask, render_template, request, redirect, flash, url_for, session, Response, jsonify, Blueprint, current_app

bp = Blueprint('opacity', __name__, template_folder="../templates/bias", url_prefix="/opacity")

@bp.route('/', methods=['GET'])
def opacity_home():
    return "<p>Hello, World!</p>"

frontend/templates/bias/base.html
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %} {% endblock %}</title>
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
</head>

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class=flashes>
    {% for category, message in messages %}
	<div class="alert alert-{{ category }}" role="alert">
	     {{ message }} 
	</div>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

<body>
    
    {% block content %}
    {% endblock %}

    {% block scripts %}
    {% endblock %}
    
    {% block footer %}
    {% endblock %}
</body>
</html>

frontend/templates/bias/freqvsfreq.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block title %}
FreqvsFreq
{% endblock %}

{% block content %}
<div class="px-4 py-5 my-2 text-center">
	<h1 class="display-5 fw-bold text-body-emphasis">Freq vs Freq Analysis</h1>
	<div class="col-lg-6 mx-auto">
	<p class="lead mb-4">Check how much the predictions for the target variable differ with respect to the categories of a "root variable", overall and conditioned to the categories of other selected predictors. <br>
    Using the max as aggregating function, you are checking the "worst case scenario".
    Using the min as aggregating function, you are checking the "best case scenario".</p>
</div>
{% include 'bias/upload_freqvsfreq.html' %}
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/handle_parameters.js') }}"></script>
<script type="text/javascript">
function handle_agg_funcs() {
  let data = new FormData();
  var rootvar = document.getElementById("root_var");
  var selected_option = rootvar.options[rootvar.selectedIndex];
  data.append("rv_selected", selected_option.value);
  const freqvsfreq_url = "http://" + "{{ local_ip }}" + ":5000/bias/freqvsfreq";
  
  fetch(freqvsfreq_url, {
    "method": "POST",
    "body": data
  })
  .then((response) => response.json())
  .then((data) => {
    // Handle the received data
    // If the response is "True", show only the "Max" button and select it
    // If the response is "False", enable all buttons
    const buttons = document.querySelectorAll('input[name="agg_func"]');
    if (data.response === "True") {
      buttons.forEach(button => {
        button.disabled = true;
      });
      document.getElementById("agg_func2").checked = true;
    } else {
      buttons.forEach(button => {
        button.disabled = false;
      });
    }
  })
  .catch(error => {
    console.error('Error:', error);
  });
}

function display_thr() {
  var auto_thr = document.getElementById("auto_thr")
  var params = document.getElementById("a1_params")
  console.log(auto_thr.checked)
  if (auto_thr.checked == true) {
    params.classList.remove("d-none");
  } else {
    params.classList.add("d-none");
  }
};

function display_nbins() {
  var target_type1 = document.getElementById("target_type1")
  var target_type2 = document.getElementById("target_type2")
  var nbins = document.getElementById("binning")
  if (target_type2.checked == true) {
    nbins.classList.remove("d-none");
  } else if (target_type1.checked == true) {
    nbins.classList.add("d-none");
  }
};

document.addEventListener("DOMContentLoaded", function() {
    var disabfromroot = document.getElementById("root_var");
    disabfromroot.addEventListener("change", handle_agg_funcs);
    var auto_thr = document.getElementById("auto_thr");
    auto_thr.addEventListener("change", display_thr)
    var tgtype1= document.getElementById("target_type1");
    tgtype1.addEventListener("change", display_nbins)
    var tgtype2= document.getElementById("target_type2");
    tgtype2.addEventListener("change", display_nbins)
});

</script>
{% endblock %}

{% block footer %}
    <div class="modal-footer">
        <a href="/bias/freqvsfreq/results"><button type="button" class="btn btn-secondary btn-semixl" data-dismiss="modal">Run</button>
    </div>
{% endblock %}

frontend/templates/bias/freqvsref.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block title %}
FreqvsRef
{% endblock %}

{% block content %}
<div class="px-4 py-5 my-2 text-center">
	<h1 class="display-5 fw-bold text-body-emphasis">Freq vs Ref Analysis</h1>
	<div class="col-lg-6 mx-auto">
	<p class="lead mb-4">Check how much the predictions for the target variable differ with respect to a reference distribution provided as input, overall and conditioning to the categories of other selected predictors. <br>
Using the max as aggregating function, you are checking the "worst case scenario". Using the min as aggregating function, you are checking the "best case scenario"..</p>
</div>
{% include 'bias/upload_freqvsref.html' %}
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/handle_parameters.js') }}"></script>
<script type="text/javascript">
function handle_refs() {
    let data = new FormData();
    var rootvar = document.getElementById("root_var");
    var selected_option_rv = rootvar.options[rootvar.selectedIndex];
    var predvar = document.getElementById("predictions");
    var selected_option_pr = predvar.options[predvar.selectedIndex];  
    var target_type1 = document.getElementById("target_type1");
    var target_type2 = document.getElementById('target_type2');
    if (target_type1.checked) {
      var selected_option_tt = target_type1;
    } else {
      var selected_option_tt = target_type2;
    }
    var nbins = document.getElementById("binning");
    var selected_option_nb = nbins.querySelector('input[name="nbins"]');
    
    if (selected_option_pr.value != "id" && selected_option_rv.value != "id") {
      data.append("rv_selected", selected_option_rv.value);
      data.append("pr_selected", selected_option_pr.value);

      data.append("tt_selected", selected_option_tt.value);
      data.append("nb_selected", selected_option_nb.value);
      const freqvsref_url = "http://" + "{{ local_ip }}" + ":5000/bias/freqvsref";
      const preds_id = document.getElementById("ref_dist");
      fetch(freqvsref_url, {
      "method": "POST",
      "body": data
          }).then((response) => response.json())
        .then((data) => {
          preds_id.innerHTML = data.response_refs;
        })
  } 
};

function handle_agg_funcs() {
  let data = new FormData();
  var rootvar = document.getElementById("root_var");
  var selected_option_rv = rootvar.options[rootvar.selectedIndex];
  var predvar = document.getElementById("predictions");
  var selected_option_pr = predvar.options[predvar.selectedIndex];
  if (selected_option_pr.value != predvar.options[0].value && selected_option_rv.value != rootvar.options[0].value) {
    data.append("rv_selected", selected_option_rv.value);
    data.append("pr_selected", selected_option_pr.value);
    const freqvsref_url = "http://" + "{{ local_ip }}" + ":5000/bias/freqvsref";
    const preds_id = document.getElementById("ref_dist");
    fetch(freqvsref_url, {
    "method": "POST",
    "body": data
        }).then((response) => response.json())
      .then((data) => {
        preds_id.innerHTML = data.response_refs;
      })
  }
};

function display_thr() {
  var auto_thr = document.getElementById("auto_thr")
  var params = document.getElementById("a1_params")
  console.log(auto_thr.checked)
  if (auto_thr.checked == true) {
    params.classList.remove("d-none");
  } else {
    params.classList.add("d-none");
  }
};

function display_nbins() {
  var target_type1 = document.getElementById("target_type1")
  var target_type2 = document.getElementById("target_type2")
  var nbins = document.getElementById("binning")
  if (target_type2.checked == true) {
    nbins.classList.remove("d-none");
  } else if (target_type1.checked == true) {
    nbins.classList.add("d-none");
  }
};

document.addEventListener("DOMContentLoaded", function() {
    var fromroot = document.getElementById("root_var");
    var frompred = document.getElementById("predictions");
    fromroot.addEventListener("change", handle_refs);
    frompred.addEventListener("change", handle_refs);
    var auto_thr = document.getElementById("auto_thr");
    auto_thr.addEventListener("change", display_thr)
    var tgtype1= document.getElementById("target_type1");
    tgtype1.addEventListener("change", display_nbins)
    var tgtype2= document.getElementById("target_type2");
    tgtype2.addEventListener("change", display_nbins)
});
</script>
{% endblock %}

{% block footer %}
    <div class="modal-footer">
        <a href="/bias/freqvsref/results"><button type="button" class="btn btn-secondary btn-semixl" data-dismiss="modal">Run</button>
    </div>
{% endblock %}

frontend/templates/bias/home.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block title %}
Homepage
{% endblock %}


{% block content %}
<div class="px-4 py-5 my-2 text-center parent-img">
  <div class="img-container">
    <img class="imgback" src="{{ url_for('static', filename='BRIO_banner.png') }}" width="1000" height="200">
    <img class="imgfront" src="{{ url_for('static', filename='alkemy.png') }}" alt="" width="72" height="72">
  </div>
  <h1 class="display-5 fw-bold text-body-emphasis">BRIO X Alkemy <br> A bias and risk detection tool for ML models</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Developed within the scope of the industrial partnership between BRIO and Alkemy.</p>
  </div>
  {% include 'bias/upload_home.html' %}
  <div class="card mx-auto mt-2" style="width: 14rem;">
    <div class="card-body {{ status }}">
      <h5 class="card-title">Currently uploaded dataframe:</h5>
      <p class="card-text">{{ df_used }}</p>
      <a href="/bias?reset=True" class="card-link">Reset</a>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
<div class="d-grid gap-2 d-sm-flex justify-content-sm-center my-3">
	<a href={{url_for("freqvsfreq")}} style="display: inline-block; margin-right: 20px; bottom: 200px; right: 200px;"><button class="btn btn-primary btn-lg px-4 gap-3" type="button">Freq vs freq analysis</button></a>
    <a href={{url_for("freqvsref")}} style="display: inline-block; right: 200px; bottom: 200px;"><button class="btn btn-primary btn-lg px-4 gap-3" type="button">Freq vs ref analysis</button></a>
</div>
{% endblock %}

frontend/templates/bias/ref_dist.html
<div class="row">
    <div class="col-3">
        <input type="number" class="form-control" placeholder="" name="prob_a_0" id="prob_a_0" min="0" max="1" step=".01">
    </div>
    <div class="col-3">
        <input type="number" class="form-control" placeholder="" name="prob_a_1" id="prob_a_1" min="0" max="1" step=".01">
    </div>
    <div class="col-3">
        <input type="number" class="form-control" placeholder="" name="prob_b_0" id="prob_b_0" min="0" max="1" step=".01">
    </div>
    <div class="col-3">
        <input type="number" class="form-control" placeholder="" name="prob_b_1" id="prob_b_1" min="0" max="1" step=".01">
    </div>
</div>

frontend/templates/bias/results_freqvsfreq.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block title %}
Results
{% endblock %}

{% block content %}
<div class="container my-5 mx-5 shadow-lg rounded-3">
  <div class="row mx-3 pe-lg-0 pt-lg-5">
    <div class="col border border-5 mx-4">
      <h2 class="display-6 fw-bold text-center">Overall Result</h2>
      <p class="text-center" style="font-size: 24px;">
      (Distance, distance&lt;&#61;threshold, threshold, standard deviation)
      </p>
      <p class="text-center" style="font-size: 24px;">
      ({{ results1[0] }}, <b><span {% if results1[1] %}class="green-text"{% else %}class="red-text"{% endif %}>{{ results1[1] }}</span></b> , {{ results1[2] }}, {{ results1[3] }})
      </p>
    </div>
  </div>
  <div class="row pb-4 mx-3 pe-lg-0 pt-lg-5">
    <div class="col border border-5 mx-1">
      <h2 class="display-6 red-text fw-bold text-center">Violations</h2>
      <p style="font-size: 18px;">
      Condition: (num observations, distance, distance&lt;&#61;threshold, threshold, standard deviation)
      </p>
      {% for key, value in violations.items() %}
        {% if violations|length != 1 %}
          <div style="color: rgba(255, {{ 160*((loop.index - 1) / (violations|length - 1)) }}, 0, 1);">
            <a href='/bias/freqvsfreq/results/{{ key }}'>{{ key }}</a> : {{ value }}<br>
          </div>
        {% endif %}
      {% endfor %} 
    </div>
    <div class="col border border-5 mx-1">
      <h2 class="display-6 fw-bold text-center">Conditioned Results  <button class="btn btn-primary btn-export" id="export-btn">Export CSV</button></h2>
      <div class="row">
        <div class="col text-center">
          <h4 class="fw-bold">Condition applied</h4>
        </div>
        <div class="col text-center">
          <h4 class="fw-bold">Result</h4>
        </div>
      </div>
      {% for key, value in results2.items() %}
        <div class="row">
          <div class="col text-center">
            {{ key }}
          </div>
          <div class="col text-center">
            ({{ value[0] }}, {{ value[1] }}, <span {% if value[2] == True %}class="green-text"{% elif value[2] == False %}class="red-text"{% endif %}>{{ value[2] }}</span>, {{ value[3] }})
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
function handle_export() {
  const results_url = "http://" + "{{ local_ip }}" + ":5000/bias/freqvsfreq/results";
  fetch(results_url, {
    "method": "POST",
    "headers" : {
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    },
    "body": JSON.stringify({ "export-data": "True"})
  })
  .then((response) => response.json())
  .then((data) => {
    // Handle the received data
    const blob = new Blob([data.csv_data], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'conditioned_results.csv';
    link.style.display = 'none';
    // Trigger the download
    document.body.appendChild(link);
    link.click();
    // Clean up
    document.body.removeChild(link);
  })
  .catch(error => {
    console.error('Error:', error);
  })
};

document.addEventListener("DOMContentLoaded", function() {
    var disabfromroot = document.getElementById("export-btn");
    disabfromroot.addEventListener("click", handle_export);
});
</script>
{% endblock %}

frontend/templates/bias/results_freqvsref.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block title %}
Results
{% endblock %}

{% block content %}
<div class="container my-5 mx-5 shadow-lg rounded-3">
  <div class="row mx-3 pe-lg-0 pt-lg-5">
    <div class="col border border-5 mx-4">
      <h2 class="display-6 fw-bold text-center">Overall Result</h2>
      <p class="text-center" style="font-size: 24px;">
      (Distance&lsqb;ref&rsqb;, distance&lsqb;ref&rsqb;&lt;&#61;threshold, threshold)
      </p>
      <p class="text-center" style="font-size: 24px;">
      ({{ results1[0] }}, <b><span {% if results1[1][1] %}class="green-text"{% else %}class="red-text"{% endif %}>{{ results1[1] }}</span></b>, {{ results1[2] }})
      </p>
    </div>
  </div>
  <div class="row pb-4 mx-3 pe-lg-0 pt-lg-5">
    <div class="col border border-5 mx-1">
      <h2 class="display-6 red-text fw-bold text-center">Violations</h2>
      <p style="font-size: 18px;">
      Condition: (num observations, distance&lsqb;ref&rsqb;, distance&lsqb;ref&rsqb;&lt;&#61;threshold, threshold)
      </p>
      {% for key, value in violations.items() %}
        {% if violations|length != 1 %}
          <div style="color: rgba(255, {{ 160*((loop.index - 1) / (violations|length - 1)) }}, 0, 1);">
            <a href='/bias/freqvsref/results/{{ key }}'>{{ key }}</a> : {{ value }}<br>
          </div>
        {% endif %}
      {% endfor %} 
    </div>
    <div class="col border border-5 mx-1">
      <h2 class="display-6 fw-bold text-center">Conditioned Results  <button class="btn btn-primary btn-export" id="export-btn">Export CSV</button></h2>
      <div class="row">
        <div class="col text-center">
          <h4 class="fw-bold">Condition applied</h4>
        </div>
        <div class="col text-center">
          <h4 class="fw-bold">Result</h4>
        </div>
      </div>
      {% for key, value in results2.items() %}
        <div class="row">
          <div class="col text-center">
            {{ key }}
          </div>
          <div class="col text-center">
            ({{ value[0] }}, {{ value[1] }}, <span {% if value[2] == True %}class="green-text"{% elif value[2] == False %}class="red-text"{% endif %}>{{ value[2] }}</span>, {{ value[3] }})
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript">
function handle_export() {
  const results_url = "http://" + "{{ local_ip }}" + ":5000/bias/freqvsref/results";
  fetch(results_url, {
    "method": "POST",
    "headers" : {
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    },
    "body": JSON.stringify({ "export-data": "True"})
  })
  .then((response) => response.json())
  .then((data) => {
    // Handle the received data
    const blob = new Blob([data.csv_data], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'conditioned_results.csv';
    link.style.display = 'none';
    // Trigger the download
    document.body.appendChild(link);
    link.click();
    // Clean up
    document.body.removeChild(link);
  })
  .catch(error => {
    console.error('Error:', error);
  })
};

document.addEventListener("DOMContentLoaded", function() {
    var disabfromroot = document.getElementById("export-btn");
    disabfromroot.addEventListener("click", handle_export);
});
</script>
{% endblock %}

frontend/templates/bias/upload_home.html
{% block content %}
<h2>Upload files</h2><br>
<form method="POST" action="{{ url_for('bias.home_bias') }}" enctype="multipart/form-data">
    <div class="form-group row mb-2 w-50 mx-auto">
	    <label for="dataset" class="col-sm-2 col-form-label col-form-label-lg font-weight-bold">Dataframe:</label>
	    <div class="col-sm-10">
        <input type="file" class="form-control form-control-lg ml-4" name="dataset" id="dataset">
	    </div>
	    <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#exampleModal">
	      Customize your preprocessing pipeline here
	    </button>
    </div>
    <button type="submit" class="btn btn-secondary btn-lg ml-3 mx-auto">Upload</button>
</form>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Preprocessing customization</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>
        You can upload here a raw dataset, a preprocessing pipeline in the form of a jupyter notebook (packages you use must already be installed), and some artifacts. Please note that if you use this customization tool, <u>the original dataframe will be overridden</u>. Notebooks input can be accessed at <b>os.path.abspath("uploads/input_file")</b>. Output dataframe should be a <u>pickle</u> file located at <b>os.path.abspath("uploads/output_file")</b>.
        </p>
        <form method="POST" action="{{ url_for('bias.home_bias') }}" enctype="multipart/form-data">
          <div class="form-group row mb-2 mx-auto">
	    <label for="dataset_custom" class="col-sm-2 col-form-label col-form-label-sm font-weight-bold">Dataset:</label>
            <div class="col-sm-10">
              <input type="file" class="form-control form-control-sm" name="dataset_custom" id="dataset_custom"><br> 
            </div><br><br>
            <label for="notebook" class="col-sm-2 col-form-label col-form-label-sm font-weight-bold">Notebook:</label>
            <div class="col-sm-10">
              <input type="file" class="form-control form-control-sm" name="notebook" id="notebook">
            </div><br><br>
            <label for="artifacts" class="col-sm-2 col-form-label col-form-label-sm font-weight-bold">Artifacts:</label>
            <div class="col-sm-10">
              <input type="file" class="form-control form-control-sm" name="artifacts" id="artifacts" multiple>
            </div><br>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-secondary" id="upload_preprocess">Upload</button>
        </div>
        </form>
    </div>
  </div>
</div>
{% endblock %}